.PHONY: all clean

BINUTILS_VERSION=2.30
GCC_VERSION=7.3.0

all:
	./build_all.sh ${BINUTILS_VERSION} ${GCC_VERSION}

clean:
	rm -rf build-gcc build-binutils binutils-${BINUTILS_VERSION} gcc-${GCC_VERSION} *.tar.*

