#define ISR_FUNCTION_NAME(num) isr##num
#define ISR_FUNCTION_DEF(num) extern "C" void ISR_FUNCTION_NAME(num) ()

ISR_FUNCTION_DEF(0);
ISR_FUNCTION_DEF(1);
ISR_FUNCTION_DEF(2);
ISR_FUNCTION_DEF(3);
ISR_FUNCTION_DEF(4);
ISR_FUNCTION_DEF(5);
ISR_FUNCTION_DEF(6);
ISR_FUNCTION_DEF(7);
ISR_FUNCTION_DEF(8);
ISR_FUNCTION_DEF(9);
ISR_FUNCTION_DEF(10);
ISR_FUNCTION_DEF(11);
ISR_FUNCTION_DEF(12);
ISR_FUNCTION_DEF(13);
ISR_FUNCTION_DEF(14);
ISR_FUNCTION_DEF(15);
ISR_FUNCTION_DEF(16);
ISR_FUNCTION_DEF(17);
ISR_FUNCTION_DEF(18);
ISR_FUNCTION_DEF(19);
ISR_FUNCTION_DEF(20);
ISR_FUNCTION_DEF(21);
ISR_FUNCTION_DEF(22);
ISR_FUNCTION_DEF(23);
ISR_FUNCTION_DEF(24);
ISR_FUNCTION_DEF(25);
ISR_FUNCTION_DEF(26);
ISR_FUNCTION_DEF(27);
ISR_FUNCTION_DEF(28);
ISR_FUNCTION_DEF(29);
ISR_FUNCTION_DEF(30);
ISR_FUNCTION_DEF(31);
